# Generated by Django 5.1 on 2024-08-13 16:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='mdbId',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='artist',
            name='mdbId',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='song',
            name='mdbId',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
