# Generated by Django 5.1 on 2024-08-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_usertrack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='img_url',
        ),
    ]
